### ISSUE TITLE
Not compatible with Feature Extensions API

### ISSUE THREAD

**Issue by Christoph-Koehler** [miltoncandelero/pixi-webfont-loader#13]
It does not seem to be compatible with the _Feature Extensions API_ which was introduced in [v6.5.0](https://github.com/pixijs/pixijs/releases/tag/v6.5.0).
When trying to add webfont-loader with `PIXI.extensions.add(WebfontLoaderPlugin);` I am getting the following error:

"Extension class must have an extension object"

**Comment by miltoncandelero** [comment]
This is a plugin for the `Loader` class and can't be used with the new `Assets` class. However, `Assets` can load webfonts without the need for a plugin so if you migrate to the `Assets` class you no longer need this plugin.

If you are still using the `Loader`, keep using the old way of registering the plugin and it should still work.
