### ISSUE TITLE
Load both .woff2 and .woff files using the same name

### ISSUE THREAD

**Issue by pigszel** [miltoncandelero/pixi-webfont-loader#7]
Hello there,

First of all, thank you for this plugin, it saved my life.

I was just wondering that is there any chance to load both .woff2 and .woff files of the font using the same name?
Because if I am trying to do so, I got the following error:

`Uncaught Error: Resource named "My-Awesome-Font-Bold" already exists.`

Here is my example code: 

```
PIXI.Loader.shared.add({ name: "My-Awesome-Font-Bold", url: `${BASE_URL}/fonts/MyAwesomeFont-Bold.woff2` });
PIXI.Loader.shared.add({ name: "My-Awesome-Font-Bold", url: `${BASE_URL}/fonts/MyAwesomeFont-Bold.woff` });
PIXI.Loader.shared.add({ name: "My-Awesome-Font-Medium", url: `${BASE_URL}/fonts/MyAwesomeFont-Medium.woff2` });
PIXI.Loader.shared.add({ name: "My-Awesome-Font-Medium", url: `${BASE_URL}/fonts/MyAwesomeFont-Medium.woff` });
```

Thank you in advance.

**Comment by miltoncandelero** [comment]
Why are you trying to load both woff and woff2 fonts for the same font? 🤔 

If it is for internet explorer compatibility you might have to create a css style and load that file instead 🤔

Otherwise using only the woff2 should be enough...

**Comment by pigszel** [comment]
Since I have a very wide range of supportable browsers, I thought it would be awesome if I could load both.
But if it's not feasible, I am completely okay with it, since this plugin is working perfectly.
